# Generated by Django 4.0.4 on 2022-05-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('studid', models.IntegerField()),
                ('department_list', models.CharField(blank=True, choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('studentId', models.IntegerField()),
                ('phoneNumber', models.IntegerField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=200, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('emailStudent', models.EmailField(max_length=254)),
                ('GPA', models.IntegerField()),
                ('level', models.CharField(blank=True, choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth')], max_length=200, null=True)),
                ('active', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'ourstudent',
            },
        ),
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('passWord', models.IntegerField()),
            ],
        ),
    ]
